apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::652584088648:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-nF8kjfzUhEhs
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::652584088648:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-15T18:56:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1272"
  uid: ef330aa3-0ce0-46ea-8d1f-a7cabdc4318c
